
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_Case;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Col1 = @"брутална агресия между съседи",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");


Console.WriteLine($"Col0: {@"Наказателно право"}");
Console.WriteLine($"Col1: {@"брутална агресия между тийнейджъри в столичен мол. Младежи пребиха момиче и сами заснеха деянието"}");


Console.WriteLine($"\n\nPredicted Col0: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

