
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp121;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Content = @"нападнаха ме и ме пребиха",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Name with predicted Name from sample data...\n\n");


Console.WriteLine($"Name: {@"Наказателно право"}");
Console.WriteLine($"Content: {@"нападнаха ме и ме пребиха"}");


Console.WriteLine($"\n\nPredicted Name: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

